# Generated by Django 5.0.2 on 2024-03-10 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0003_remove_leavesummary_employee_leavesummary_employee'),
        ('projectmanager', '0008_alter_projmanager_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='managers',
            field=models.ManyToManyField(blank=True, to='projectmanager.projmanager'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=30),
        ),
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('Approve', 'Approve'), ('Reject', 'Reject'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leave_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_management.leaveapplication')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.projmanager')),
            ],
        ),
    ]
