# Generated by Django 5.0.2 on 2024-03-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0005_delete_leaveapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='approval_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='rejection_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
