# Generated by Django 5.0.2 on 2024-03-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0007_managerapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerapproval',
            name='decision',
            field=models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=10),
        ),
    ]
