# Generated by Django 5.0.2 on 2024-03-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0009_remove_leaveapplication_approval_count_and_more'),
        ('projectmanager', '0008_alter_projmanager_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='managers',
            field=models.ManyToManyField(blank=True, to='projectmanager.projmanager'),
        ),
        migrations.DeleteModel(
            name='LeaveApproval',
        ),
    ]
