# Generated by Django 5.0.2 on 2024-03-10 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0010_leaveapplication_managers_delete_leaveapproval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='managers',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='status',
        ),
    ]
