# Generated by Django 5.0.2 on 2024-03-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0011_remove_leaveapplication_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='manager_response',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=30),
        ),
    ]
