# Generated by Django 5.0.2 on 2024-03-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0013_remove_leaveapplication_manager_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='manager_response_field',
            field=models.JSONField(default=dict),
        ),
    ]
