# Generated by Django 5.0.2 on 2024-03-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0014_leaveapplication_manager_response_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='admin_response',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='manager_response_field',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='status',
        ),
    ]
