# Generated by Django 5.0.2 on 2024-03-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0015_remove_leaveapplication_admin_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
