# Generated by Django 5.0.2 on 2024-03-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0016_leaveapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='approvals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='rejections',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
