# Generated by Django 5.0.2 on 2024-03-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0017_leaveapplication_approvals_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='approvals',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='rejections',
        ),
    ]
