# Generated by Django 5.0.2 on 2024-03-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0021_alter_leaveapplication_status_manageraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.DeleteModel(
            name='ManagerAction',
        ),
    ]
