# Generated by Django 5.0.2 on 2024-03-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0022_alter_leaveapplication_status_delete_manageraction'),
        ('projectmanager', '0008_alter_projmanager_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='managers',
            field=models.ManyToManyField(blank=True, to='projectmanager.projmanager'),
        ),
    ]
