# Generated by Django 5.0.2 on 2024-03-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0023_leaveapplication_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='superuser_changed_status',
            field=models.BooleanField(default=False),
        ),
    ]
