# Generated by Django 5.0.2 on 2024-03-19 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0024_leaveapplication_superuser_changed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavesummary',
            name='leave_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leave_management.leavetype'),
        ),
    ]
