# Generated by Django 5.0.2 on 2024-03-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0025_leavesummary_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
