# Generated by Django 5.0.2 on 2024-03-26 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0029_remove_leaveapplication_submitted_by_and_more'),
        ('projectmanager', '0012_alter_projmanager_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='final_rejection_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_rejected_leaves', to='projectmanager.projmanager'),
        ),
    ]
