# Generated by Django 5.0.2 on 2024-03-26 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0031_leaveapplication_effective_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveapplication',
            old_name='effective_status',
            new_name='employee_view_status',
        ),
    ]
