# Generated by Django 5.0.2 on 2024-03-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0032_rename_effective_status_leaveapplication_employee_view_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='manager_statuses',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
