# Generated by Django 5.0.2 on 2024-03-28 05:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0033_leaveapplication_manager_statuses'),
        ('projectmanager', '0012_alter_projmanager_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerLeaveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('leave_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_management.leaveapplication')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.projmanager')),
            ],
        ),
    ]
