# Generated by Django 5.0.2 on 2024-03-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0035_leavesummary_previous_state_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavesummary',
            name='previous_state_available',
        ),
        migrations.RemoveField(
            model_name='leavesummary',
            name='previous_state_used',
        ),
    ]
