# Generated by Django 5.0.2 on 2024-04-02 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0036_remove_leavesummary_previous_state_available_and_more'),
        ('projectmanager', '0013_projmanager_first_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerLeaveSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_available', models.PositiveIntegerField(default=0)),
                ('total_used', models.PositiveIntegerField(default=0)),
                ('leave_type', models.ManyToManyField(to='leave_management.leavetype')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.projmanager')),
            ],
        ),
    ]
