# Generated by Django 5.0.2 on 2024-03-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employee_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.IntegerField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
