# Generated by Django 5.0.2 on 2024-03-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_employee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.IntegerField(max_length=128),
        ),
    ]
