# Generated by Django 5.0.2 on 2024-03-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0010_alter_projmanager_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projmanager',
            name='password',
            field=models.IntegerField(max_length=128),
        ),
    ]
