# Generated by Django 5.0.2 on 2024-03-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0012_alter_projmanager_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='projmanager',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
