# Generated by Django 5.0.2 on 2024-03-10 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employee_is_manager'),
        ('notifications', '0002_alter_leavenotification_options_and_more'),
        ('projectmanager', '0008_alter_projmanager_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavenotification',
            name='leave_application',
        ),
        migrations.AddField(
            model_name='leavenotification',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='leavenotification',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='projectmanager.projmanager'),
        ),
    ]
