# Generated by Django 5.0.2 on 2024-03-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_leavenotification_leave_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavenotification',
            name='notification_read_status',
            field=models.BooleanField(default=False),
        ),
    ]
