# Generated by Django 5.0.2 on 2024-03-29 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_employee_first_login'),
        ('notifications', '0004_leavenotification_notification_read_status'),
        ('projectmanager', '0013_projmanager_first_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerToEmployeeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_read_status', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to='employees.employee')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='projectmanager.projmanager')),
            ],
        ),
    ]
